### ISSUE TITLE
Представиться

### ISSUE THREAD

**Issue by pepelsbey** [talgautb/frontender#20]
> Спасибо за помощь, редактор talgautb

Всех по именам, а редактор «тальгаутб» со строчной. Представьтесь, так будет солиднее.

**Comment by talgautb** [comment]
@pepelsbey А почему с мягким знаком?)
Спасибо :)

**Comment by pepelsbey** [comment]
@talgautb, слово незнакомое, фантазирую как умею )

**Comment by pepelsbey** [comment]
Хм, задача закрыта, а редактор всё ещё @talgautb, непорядок

**Comment by talgautb** [comment]
fix @pepelsbey
