### ISSUE TITLE
По поводу "Усачёв Максим aka psyw и CEO" и "главный редактор CSS live"

### ISSUE THREAD

**Issue by psywalker** [talgautb/frontender#6]
Здравствуйте! К сожалению только сегодня увидел ваш замечательный список, но кое с чем я принципиально не согласен, и очень вас прошу внести кое-какие правки. 

Дело в том, что там, где указано моё имя (буква "У"), есть следующая информация: "CEO и главный редактор CSS live (сайт, @psyw)". Я не могу с этим согласиться по нескольким причинам.
1. Автором сайта css-live.ru являюсь не только я, но также и мой соавтор Илья Стрельцын (@SelenIT2)
2. Главным редактором на этом сайте является именно Илья Стрельцын, а не я. 

Поэтому у меня к вам огромная просьба. Внесите пожалуйста имя моего коллеги в ваш список, либо допишите рядом с моими инициалами и его тоже. Так будет честно, и мне не будет стыдно перед сообществом, и главное, перед моим другом. 

Заранее благодарю!

**Comment by talgautb** [comment]
@psywalker большинство формулировок я брал из интернета, хотя точно не вспомню конкретно откуд взял информацию о Вас :)
Вы можете всегда отправить PR если с чем-то не согласны, либо напишите формулировку, которая Вас устроит, а я добавлю.

**Comment by talgautb** [comment]
А что скажите по поводу [этого](https://vk.com/club36238567) ?) @psywalker 
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_56954/2FTEl2EJZTcOlp5pi9UjkjVJQ78MFV/CSS-live%2B%25E2%2580%2593%2B%25D0%25A1%25D0%25BE%25D0%25BE%25D0%25B1%25D1%2589%25D0%25B5%25D1%2581%25D1%2582%25D0%25B2%25D0%25BE%2B%25D0%25BF%25D1%2580%25D0%25BE%2BHTML%252C%2BCSS%2B%25D0%25B8%2BJavaScript%2B2015-07-13%2B11-52-19.png?Expires=1436853176&Signature=F9BXKRYnERe6I76YCsrw~0WuOs~iZ2KpPrCLL8dDXWVmc2kYU2nznQ8qTJtG-CsZSEnty4sEqmAzrNHsYtzu39GKYR9I8X8BUeUdW5hr7fY3Tu4rORpIpMwC36ejF8tgMLISl~VqqL-Nd32Obx8VkihwQGCyhWK--x3dX1uz66m~4yQe8r1ZRD-bwB6PgMWmq~z5JSojydJs~U-YNQQ5nF~c~Layti4Pb3njf4KdcI08CIMojyRnxQwHC5JTlyTXyTEQ9EiW5e666m6CsoHavtw7pbJ3ecy9sglk-Nhmiei6rfFtZFOr5C75tpC~KngJAS-XKsqBSmUujzrtm~mz7Q__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by psywalker** [comment]
Да нет, PR необязателен. Считаю, что было бы честным сделать так: 

1. Взять отдельную букву "И" и добавить туда текст
 "Илья Стрельцын  
Соавтор и главный редактор сайта CSS live
сайт, @SelenIT2"

2. А текст, который связан со мной, заменить на:
"CEO и автор сайта CSS live
сайт, @psyw"

----

Что касается группы в вк, информацию забивал не я, а наш помощник (который уже не работает с нами), но сегодня я её исправил: http://screencast.com/t/aVRLmTUX
