### ISSUE TITLE
Имена и никнеймы

### ISSUE THREAD

**Issue by talgautb** [talgautb/frontender#7]
поменять сочетание `aka` на что-нибудь другое.
сейчас
### Фамилия Имя aka никнейм

**Comment by igoradamenko** [comment]
Юля «yoksel» Бухвалова, например? Но список отсортирован по фамилиям, так что: Бухвалова Юля (yoksel) и всё, не?

**Comment by talgautb** [comment]
@igoradamenko смущают скобки :)

**Comment by igoradamenko** [comment]
@talgautb ну мы же тут не препроцессор выбираем) ещё вот такой вариант:

### Бухвалова Юля `yoksel`

**Comment by h4** [comment]
Ещё далеко не у всех есть постоянный ник. Например, Никита Прокопов. Да и у Андрея Ситника раньше был ai, а теперь он почти везде отреберндился

**Comment by talgautb** [comment]
@h4 согласен, возможно стоит убрать. а в ссылках на твиттер указывать никнейм (как сейчас и делается)

**Comment by talgautb** [comment]
Подумав, решил убрать никнеймы возле имени и фамилии
